---
# Dataset
$schema: https://schemas.opendatacube.org/dataset
id: 04dacb82-0d7e-4e6e-8dfb-0b2326776fd2

label: ga_s2bm_ard_provisional_3-2-1_56JNQ_2021-07-24_interim
product:
  name: ga_s2bm_ard_provisional_3
  href: https://collections.dea.ga.gov.au/product/ga_s2bm_ard_provisional_3

crs: epsg:32756
geometry:
  type: Polygon
  coordinates: [[[499980.0, 6989961.499130024], [499980.0, 6990104.681164242], [499980.0,
        6990200.624788773], [501750.29857499857, 6997392.42535625], [502330.31082289375,
        6999702.473832453], [502417.0835269785, 7000000.0], [502473.62789648306, 7000000.0],
      [502474.82785600686, 7000000.0], [609780.0, 7000000.0], [609780.0, 6890200.0],
      [499980.0, 6890200.0], [499980.0, 6989961.499130024]]]
grids:
  default:
    shape: [10980, 10980]
    transform: [10.0, 0.0, 499980.0, 0.0, -10.0, 7000000.0, 0.0, 0.0, 1.0]
  '20':
    shape: [5490, 5490]
    transform: [20.0, 0.0, 499980.0, 0.0, -20.0, 7000000.0, 0.0, 0.0, 1.0]
  '60':
    shape: [1830, 1830]
    transform: [60.0, 0.0, 499980.0, 0.0, -60.0, 7000000.0, 0.0, 0.0, 1.0]

properties:
  datetime: 2021-07-24 23:54:25.977963Z
  dea:dataset_maturity: interim
  dea:product_maturity: provisional
  eo:cloud_cover: 0.5215020755694261
  eo:constellation: sentinel-2
  eo:gsd: 10.0  # Ground sample distance (m)
  eo:instrument: MSI
  eo:platform: sentinel-2b
  eo:sun_azimuth: 34.3454544790251
  eo:sun_elevation: 55.20728069395
  fmask:clear: 27.209523656110935
  fmask:cloud: 0.5215020755694261
  fmask:cloud_shadow: 0.3372225315653116
  fmask:snow: 0.07256729430008464
  fmask:water: 71.85918444245424
  gqa:abs_iterative_mean_x: .nan
  gqa:abs_iterative_mean_xy: .nan
  gqa:abs_iterative_mean_y: .nan
  gqa:abs_x: .nan
  gqa:abs_xy: .nan
  gqa:abs_y: .nan
  gqa:cep90: .nan
  gqa:iterative_mean_x: .nan
  gqa:iterative_mean_xy: .nan
  gqa:iterative_mean_y: .nan
  gqa:iterative_stddev_x: .nan
  gqa:iterative_stddev_xy: .nan
  gqa:iterative_stddev_y: .nan
  gqa:mean_x: .nan
  gqa:mean_xy: .nan
  gqa:mean_y: .nan
  gqa:stddev_x: .nan
  gqa:stddev_xy: .nan
  gqa:stddev_y: .nan
  odc:dataset_version: 3.2.1
  odc:file_format: GeoTIFF
  odc:processing_datetime: 2021-08-10 11:43:22.636072Z
  odc:producer: ga.gov.au
  odc:product_family: ard
  odc:region_code: 56JNQ
  sentinel:datastrip_id: S2B_OPER_MSI_L1C_DS_VGS4_20210725T010111_S20210724T235247_N03.01
  sentinel:datatake_start_datetime: 2021-07-25 01:01:11Z
  sentinel:grid_square: NQ
  sentinel:latitude_band: J
  sentinel:sentinel_tile_id: S2B_OPER_MSI_L1C_TL_VGS4_20210725T010111_A022893_T56JNQ_N03.01
  sentinel:utm_zone: 56

measurements:
  nbar_blue:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band02.tif
  nbar_coastal_aerosol:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band01.tif
    grid: '60'
  nbar_green:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band03.tif
  nbar_nir_1:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band08.tif
  nbar_nir_2:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band08a.tif
    grid: '20'
  nbar_red:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band04.tif
  nbar_red_edge_1:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band05.tif
    grid: '20'
  nbar_red_edge_2:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band06.tif
    grid: '20'
  nbar_red_edge_3:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band07.tif
    grid: '20'
  nbar_swir_2:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band11.tif
    grid: '20'
  nbar_swir_3:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_band12.tif
    grid: '20'
  nbart_blue:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band02.tif
  nbart_coastal_aerosol:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band01.tif
    grid: '60'
  nbart_green:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band03.tif
  nbart_nir_1:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band08.tif
  nbart_nir_2:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band08a.tif
    grid: '20'
  nbart_red:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band04.tif
  nbart_red_edge_1:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band05.tif
    grid: '20'
  nbart_red_edge_2:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band06.tif
    grid: '20'
  nbart_red_edge_3:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band07.tif
    grid: '20'
  nbart_swir_2:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band11.tif
    grid: '20'
  nbart_swir_3:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_band12.tif
    grid: '20'
  oa_azimuthal_exiting:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_azimuthal-exiting.tif
  oa_azimuthal_incident:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_azimuthal-incident.tif
  oa_combined_terrain_shadow:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_combined-terrain-shadow.tif
  oa_exiting_angle:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_exiting-angle.tif
  oa_fmask:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_fmask.tif
    grid: '20'
  oa_incident_angle:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_incident-angle.tif
  oa_nbar_contiguity:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_nbar-contiguity.tif
  oa_nbart_contiguity:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_nbart-contiguity.tif
  oa_relative_azimuth:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_relative-azimuth.tif
  oa_relative_slope:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_relative-slope.tif
  oa_satellite_azimuth:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_satellite-azimuth.tif
  oa_satellite_view:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_satellite-view.tif
  oa_solar_azimuth:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_solar-azimuth.tif
  oa_solar_zenith:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_solar-zenith.tif
  oa_time_delta:
    path: ga_s2bm_oa_provisional_3-2-1_56JNQ_2021-07-24_interim_time-delta.tif

accessories:
  thumbnail:nbar:
    path: ga_s2bm_nbar_provisional_3-2-1_56JNQ_2021-07-24_interim_thumbnail.jpg
  thumbnail:nbart:
    path: ga_s2bm_nbart_provisional_3-2-1_56JNQ_2021-07-24_interim_thumbnail.jpg
  metadata:processor:
    path: ga_s2bm_ard_provisional_3-2-1_56JNQ_2021-07-24_interim.proc-info.yaml
  checksum:sha1:
    path: ga_s2bm_ard_provisional_3-2-1_56JNQ_2021-07-24_interim.sha1

lineage:
  level1:
  - fbcd21c3-40a7-5266-8bb4-68cc7a16abac
...
