---
# Dataset
$schema: https://schemas.opendatacube.org/dataset
id: 63cdb0d7-59a4-4c4c-a638-c52303b7fb9d

label: ga_s2am_ard_provisional_3-2-1_56HKE_2021-06-23_interim
product:
  name: ga_s2am_ard_provisional_3
  href: https://collections.dea.ga.gov.au/product/ga_s2am_ard_provisional_3

crs: epsg:32756
geometry:
  type: Polygon
  coordinates: [[[199980.0, 6000040.0], [309780.0, 6000040.0], [309780.0, 5890240.0],
      [199980.0, 5890240.0], [199980.0, 6000040.0]]]
grids:
  default:
    shape: [10980, 10980]
    transform: [10.0, 0.0, 199980.0, 0.0, -10.0, 6000040.0, 0.0, 0.0, 1.0]
  '20':
    shape: [5490, 5490]
    transform: [20.0, 0.0, 199980.0, 0.0, -20.0, 6000040.0, 0.0, 0.0, 1.0]
  '60':
    shape: [1830, 1830]
    transform: [60.0, 0.0, 199980.0, 0.0, -60.0, 6000040.0, 0.0, 0.0, 1.0]

properties:
  datetime: 2021-06-23 00:06:56.433392Z
  dea:dataset_maturity: interim
  dea:product_maturity: provisional
  eo:cloud_cover: 99.9999867286439
  eo:constellation: sentinel-2
  eo:gsd: 10.0  # Ground sample distance (m)
  eo:instrument: MSI
  eo:platform: sentinel-2a
  eo:sun_azimuth: 28.7318051318186
  eo:sun_elevation: 65.8007952652478
  fmask:clear: 0.0
  fmask:cloud: 99.9999867286439
  fmask:cloud_shadow: 0.0
  fmask:snow: 1.3271356100344725e-05
  fmask:water: 0.0
  gqa:abs_iterative_mean_x: .nan
  gqa:abs_iterative_mean_xy: .nan
  gqa:abs_iterative_mean_y: .nan
  gqa:abs_x: .nan
  gqa:abs_xy: .nan
  gqa:abs_y: .nan
  gqa:cep90: .nan
  gqa:iterative_mean_x: .nan
  gqa:iterative_mean_xy: .nan
  gqa:iterative_mean_y: .nan
  gqa:iterative_stddev_x: .nan
  gqa:iterative_stddev_xy: .nan
  gqa:iterative_stddev_y: .nan
  gqa:mean_x: .nan
  gqa:mean_xy: .nan
  gqa:mean_y: .nan
  gqa:stddev_x: .nan
  gqa:stddev_xy: .nan
  gqa:stddev_y: .nan
  odc:dataset_version: 3.2.1
  odc:file_format: GeoTIFF
  odc:processing_datetime: 2021-08-12 05:14:01.700458Z
  odc:producer: ga.gov.au
  odc:product_family: ard
  odc:region_code: 56HKE
  sentinel:datastrip_id: S2A_OPER_MSI_L1C_DS_VGS4_20210623T013035_S20210623T000241_N03.00
  sentinel:datatake_start_datetime: 2021-06-23 01:30:35Z
  sentinel:grid_square: KE
  sentinel:latitude_band: H
  sentinel:sentinel_tile_id: S2A_OPER_MSI_L1C_TL_VGS4_20210623T013035_A031344_T56HKE_N03.00
  sentinel:utm_zone: 56

measurements:
  nbar_blue:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band02.tif
  nbar_coastal_aerosol:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band01.tif
    grid: '60'
  nbar_green:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band03.tif
  nbar_nir_1:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band08.tif
  nbar_nir_2:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band08a.tif
    grid: '20'
  nbar_red:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band04.tif
  nbar_red_edge_1:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band05.tif
    grid: '20'
  nbar_red_edge_2:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band06.tif
    grid: '20'
  nbar_red_edge_3:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band07.tif
    grid: '20'
  nbar_swir_2:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band11.tif
    grid: '20'
  nbar_swir_3:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_band12.tif
    grid: '20'
  nbart_blue:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band02.tif
  nbart_coastal_aerosol:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band01.tif
    grid: '60'
  nbart_green:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band03.tif
  nbart_nir_1:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band08.tif
  nbart_nir_2:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band08a.tif
    grid: '20'
  nbart_red:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band04.tif
  nbart_red_edge_1:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band05.tif
    grid: '20'
  nbart_red_edge_2:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band06.tif
    grid: '20'
  nbart_red_edge_3:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band07.tif
    grid: '20'
  nbart_swir_2:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band11.tif
    grid: '20'
  nbart_swir_3:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_band12.tif
    grid: '20'
  oa_azimuthal_exiting:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_azimuthal-exiting.tif
  oa_azimuthal_incident:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_azimuthal-incident.tif
  oa_combined_terrain_shadow:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_combined-terrain-shadow.tif
  oa_exiting_angle:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_exiting-angle.tif
  oa_fmask:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_fmask.tif
    grid: '20'
  oa_incident_angle:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_incident-angle.tif
  oa_nbar_contiguity:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_nbar-contiguity.tif
  oa_nbart_contiguity:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_nbart-contiguity.tif
  oa_relative_azimuth:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_relative-azimuth.tif
  oa_relative_slope:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_relative-slope.tif
  oa_satellite_azimuth:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_satellite-azimuth.tif
  oa_satellite_view:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_satellite-view.tif
  oa_solar_azimuth:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_solar-azimuth.tif
  oa_solar_zenith:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_solar-zenith.tif
  oa_time_delta:
    path: ga_s2am_oa_provisional_3-2-1_56HKE_2021-06-23_interim_time-delta.tif

accessories:
  thumbnail:nbar:
    path: ga_s2am_nbar_provisional_3-2-1_56HKE_2021-06-23_interim_thumbnail.jpg
  thumbnail:nbart:
    path: ga_s2am_nbart_provisional_3-2-1_56HKE_2021-06-23_interim_thumbnail.jpg
  metadata:processor:
    path: ga_s2am_ard_provisional_3-2-1_56HKE_2021-06-23_interim.proc-info.yaml
  checksum:sha1:
    path: ga_s2am_ard_provisional_3-2-1_56HKE_2021-06-23_interim.sha1

lineage:
  level1:
  - 13bc84ae-1939-5e1e-9e9e-06a54f811fd9
...
