name: dea-env
channels:
- conda-forge/label/dev
- conda-forge
- defaults
- nodefaults
dependencies:
- basemap
- bottleneck
- bqplot
- cachetools
- cartopy
- certifi
- click
- cython
- dask
- distributed
- ephem
- fiona
- ffmpeg
- folium
- future
- gdal >=1.9
- geopandas
- geopy
- glueviz
- graphviz  # This is only graphviz itself, not the python bindings. The latter are in the pip section.
- h5py
- hdf5
- hypothesis
- ipdb
- ipyleaflet
- ipympl
- ipywidgets
- jplephem
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- jupyter_dashboards
- jupyterlab
- line_profiler
- luigi
- matplotlib
- memory_profiler
- mkl-service
- mock
- netcdf4
- nodejs
- numba
- numexpr
- numpy
- openblas
- openssl
- pandas
- pep8
- pip
- plotly
- psutil
- psycopg2
- py6s
- pylint
- pytables
- pytest
- pytest-cov
- pyyaml
- python = 3.6
- rasterio >= 1.0a12  # required for zip reading
- redis
- redis-py
- rsgislib
- rtree
- scikit-image
- scikit-learn
- scipy
- seaborn
- shapely
- singledispatch
- spectral
- sphinx
- spyder
- sqlalchemy
- tqdm
- xarray
- voluptuous
- pip:
  - autopep8
  - awscli
  - boltons
  - celery >= 4
  - ciso8601
  - click-datetime
  - compliance-checker
  - DAWG
  - flask
  - Flask-Caching
  - graphviz
  - gunicorn
  - hdmedians
  - ipython-sql
  - jupyterlab_github
  - meinheld
  - modernize
  - mypy
  - opencv-python
  - perf
  - pudb
  - pydash
  - pyDEM
  - pypeg2
  - structlog[dev]
  - yamllint
  - yappi
