name: ga_ls8c_nbart_gm_cyear_3
description: Geoscience Australia Landsat  Nadir BRDF Adjusted Reflectance Terrain, Landsat 8 Geomedian Calendar Year Collection 3
metadata_type: eo3

license: CC-BY-4.0

metadata:
  product:
    name: ga_ls8c_nbart_gm_cyear_3

measurements:
  - name: blue
    dtype: int16
    nodata: -999
    units: '1'
  - name: red
    dtype: int16
    nodata: -999
    units: '1'
  - name: green
    dtype: int16
    nodata: -999
    units: '1'
  - name: nir
    dtype: int16
    nodata: -999
    units: '1'
  - name: swir1
    dtype: int16
    nodata: -999
    units: '1'
  - name: swir2
    dtype: int16
    nodata: -999
    units: '1'
  - name: edev
    dtype: float32
    nodata: .nan
    units: '1'
  - name: sdev
    dtype: float32
    nodata: .nan
    units: '1'
  - name: bcdev
    dtype: float32
    nodata: .nan
    units: '1'
  - name: count
    dtype: int16
    nodata: -999
    units: '1'

storage:
  crs: EPSG:3577
  dimension_order:
  - time
  - y
  - x
  resolution:
    x: 30
    y: -30
  tile_size:
    x: 96000.0
    y: 96000.0
