

build-env:
	module load python3/3.6.2
	pip3 install --user yaml
	./build_environment_module.py dea-env/modulespec.yaml

build-dea:
	module load python3/3.6.2
	pip3 install --user yaml
	./build_dea_module.py
