repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3
      hooks:
        - id: yamllint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: end-of-file-fixer
        - id: check-docstring-first
        - id: check-json
        - id: check-yaml
        - id: debug-statements
        - id: name-tests-test
          args: ['--django']
        - id: requirements-txt-fixer
        - id: check-added-large-files
        - id: check-merge-conflict
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: 'v3.0.0a4'  # Use the sha / tag you want to point at
      hooks:
      - id: pylint
