---
name: ga_ls7e_level1_3
description: Geoscience Australia Landsat 7 Enhanced Thematic Mapper Plus Level 1 Collection 3
metadata_type: eo3_landsat_l1

license: CC-BY-4.0

metadata:
  product:
    name: ga_ls7e_level1_3
  properties:
     eo:platform: landsat-7
     eo:instrument: ETM
     odc:product_family: level1
     odc:producer: ga.gov.au
     landsat:collection_number: 1

measurements:
  - name: blue
    aliases:
      - band01
    dtype: uint16
    nodata: 65535
    units: '1'
  - name: green
    aliases:
      - band02
    dtype: uint16
    nodata: 65535
    units: '1'
  - name: red
    aliases:
      - band03
    dtype: uint16
    nodata: 65535
    units: '1'
  - name: nir
    aliases:
      - band04
    dtype: uint16
    nodata: 65535
    units: '1'
  - name: swir_1
    aliases:
      - band05
    dtype: uint16
    nodata: 65535
    units: '1'
  - name: swir_2
    aliases:
      - band07
    dtype: uint16
    nodata: 65535
    units: '1'
    #   - name: panchromatic
    #     aliases:
    #       - band08
    #     dtype: uint16
    #     nodata: 65535
    #     units: '1'
  - name: quality
    aliases:
      - bqa
    dtype: uint16
    nodata: 65535
    units: '1'
