source_type: ls5_pq_scene
output_type: ls5_pq_albers
metadata_type: eo

description: Landsat 5 Pixel Quality 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)

location: '/g/data/rs0/datacube/002/'
file_path_template: 'LS5_TM_PQ/{tile_index[0]}_{tile_index[1]}/LS5_TM_PQ_3577_{tile_index[0]}_{tile_index[1]}_{start_time}_v{version}.nc'
partial_ncml_path_template: 'LS5_TM_PQ/{tile_index[0]}_{tile_index[1]}/LS5_TM_PQ_3577_{tile_index[0]}_{tile_index[1]}_{start_time}.ncml'
ncml_path_template: 'LS5_TM_PQ/LS5_TM_PQ_3577_{tile_index[0]}_{tile_index[1]}.ncml'

global_attributes:
  title: Pixel Quality 25 v2
  summary: |
    The PQ25 product facilitates interpretation and processing of Surface Reflectance (SR-N/NT),  Fractional Cover 25 (FC25)
    and derivative products.

    PQ25 is an assessment of each image pixel to determine if it is an unobscured, unsaturated observation
    of the Earth surface and also whether the pixel is represented in each spectral band. The PQ product allows
    users to produce masks which can be used to exclude pixels which do not meet their quality criteria from analysis .
    The capacity to automatically exclude such pixels is essential for emerging multi-temporal analysis techniques that
    make use of every quality assured pixel within a time series of observations.\nUsers can choose to process only land pixels,
    or only sea pixels depending on their analytical requirements, leading to enhanced computationally efficient.

    PQ provides  an assessment of the quality of observations at a pixel level and includes information about:
    -	Spectral Contiguity (lack of signal in any band)
    -	Saturation in any band
    -	Presence of cloud
    -	Presence of cloud shadow
    -	Land or sea

    As Landsat Imagery becomes more readily available, there has been a rapid increase in the amount of analyses undertaken
    by researchers around the globe.  Most researchers use some form of quality masking schema in order to remove undesirable
    pixels from analysis, whether that be cloud, cloud shadow, observations over the ocean, or  saturated pixels.  In the past,
    researchers would reject partly cloud-affected scenes in favour of cloud-free scenes.  However, Landsat time series analysis
    using all cloud-free pixels has become a valuable technique and has increased the demand for automation of cloud, cloud
    shadow and saturation detection.  Emergency response applications such as flood mapping typically have to contend with
    individual cloud affected scenes and therefore rely on effective cloud and cloud shadow removal techniques.

    The PQ25 product combines established algorithms that detect clouds including the Automated Cloud Cover Assessment
    (ACCA) (Irish et al. 2006) and Function of mask (Fmask) (Zhu and Woodcock 2012) . ACCA is already widely used within the
    remote sensing community; it is fast and relatively accurate.  Fmask on the other hand is newer, but is rapidly becoming
    more established, and can provide a more accurate cloud mask than ACCA in certain cloud environments.

    The sensor saturation flagging protocols developed for the Web Enabled Landsat Data (WELD) product as described
    in Roy et al. (2011) are used to flag sensor saturation.\nThe PQ25 product has similarities to the QAB layer packaged
    with OLI data, however it uses additional algorithms to detect cloud and cloud shadow, and is available for Landsat 5, 7 and 8.
  comment: |
    -	Ground Control Points (GCP): new GCP chips released by USGS in Dec 2015 are used for re-processing
    -	Geometric QA: each product undergoes geometric assessment and the assessment result will be recorded within v2 AGDC for filtering/masking purposes.
    -	Processing parameter settings: the minimum number of GCPs for Ortho-rectified product generation has been reduced from 30 to 10.
    -	DEM: 1 second SRTM DSM is used for Ortho-rectification.
    -	Updated Calibration Parameter File (CPF): the latest/current CPF is used for processing.
  institution: Commonwealth of Australia (Geoscience Australia)
  instrument: TM
  keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,ETM+,TM,OLI,EARTH SCIENCE
  keywords_vocabulary: GCMD
  platform: LANDSAT-5
  publisher_email: earth.observation@ga.gov.au
  publisher_name: Section Leader, Operations Section, NEMO, Geoscience Australia
  publisher_url: http://www.ga.gov.au
  source: remotely observed surface reflectance and modelled cloud/shadow
  license: CC BY Attribution 4.0 International License
  cdm_data_type: Grid
  product_suite: Pixel Quality 25m
  acknowledgment: Landsat data is provided by the United States Geological Survey (USGS) through direct reception of the data at Geoscience Australias satellite reception facility or download.
  references: |
    - Berk, A., Anderson, G.P., Acharya, P.K., Hoke, M.L., Chetwynd, J.H., Bernstein, L.S., Shettle, E.P., Matthew, M.W., and Adler-Golden, S.M. (2003) Modtran 4 Version 3 Revision 1 User s manual. Airforce Research Laboratory, Hanscom, MA, USA.
    - Chander, G., Markham, B.L., and Helder, D.L. (2009) Summary of current radiometric calibration coefficients for Landsat MSS, TM, ETM+, and EO-1 ALI sensors. Remote Sensing of Environment 113, 893-903.
    - Edberg, R., and Oliver, S. (2013) Projection-Independent Earth-Solar-Sensor Geometry for Surface Reflectance Correction. Submitted to IGARSS 2013, Melbourne.
    - Forrest, R.B. (1981) Simulation of orbital image-sensor geometry, Photogrammetric Engineering and Remote Sensing 47, 1187-93.
    - GA and CSIRO (2010) 1 second SRTM Derived Digital Elevation Models User Guide. Version 1.03. GA, Canberra.
    - Irish, R. (2000) Landsat 7 Automatic Cloud Cover Assessment, sourced: http://landsathandbook.gsfc.nasa.gov/pdfs/ACCA_SPIE_paper.pdf, last accessed 12/11/2012.
    - Irons, J.R., Dwyer, J.L., and Barsi, J.A. (2012) The next Landsat satellite: The Landsat Data Continuity Mission. Remote Sensing of Environment (2012), doi:10.1016/j.rse.2011.08.026
    - Kalnay, E. Kanamitsu, M., Kistler, R., Collins, W., Deaven, D., Gandin, L., Iredell, M., Saha, S., White, G., Woollen, J., Zhu, Y., Chelliah, M., Ebisuzaki, W., Higgins, W., Janowiak, J., Mo, K.C., Ropelewski, C., Wang, J., Leetmaa, A., Reynolds, R. Jenne, R., Joseph, D. (1996) The NCEP/NCAR 40-Year Reanalysis Project. Bulletin of the American Meteorological Society 77, 437-71.
    - Li, F., Jupp, D.L.B., Reddy, S., Lymburner, L., Mueller, N., Tan, P., and Islam, A. (2010) An Evaluation of the Use of Atmospheric and BRDF Correction to Standardize Landsat Data. IEEE J. Selected Topics in Applied Earth Observations and Remote Sensing 3, 257-70.;Li, F. (2010) ARG25 Algorithm Theoretical Basis Document. GA, Canberra.
    - Li, F., Jupp, D.L.B., Thankappan, M., Lymburner, L., Mueller, N., Lewis, A., and Held, A. (2012) A physics-based atmopheric and BRDF correction for Landsat data over mountainous terrain. Remote Sensing of Environment 124, 756-70.
    - Lubke, M. (2012) Landsat Geometry Calibration/Validation Update. Presentation at LTWG #21, 25 September 2012, Sioux Falls. USGS, USA.
    - OGC (2006) OpenGIS Web Map Server Implementation Specification (Ed: Jeff de la Beaujardiere) Ref. OGC 06-042.
    - OGC (2010) OGC WCS 2.0 Interface Standard - Core. (Ed: Peter Baumann) Ref. OGC 09-110r3.
    - OGC (2013) CF-netCDF3 Data Model Extension Standard (Eds: Ben Domenico and Stefano Nativi) Ref. OGC 11-165r2.
    - Roy, D.P., Ju, J., Kline, K., Scaramuzza, P.L., Kovalskyy, V., Hansen, M., Loveland, T.R., Vermote, E., & Zhang, C. (2010). Web-enabled Landsat Data (WELD): Landsat ETM+ composited mosaics of the conterminous United States. Remote Sensing of Environment, 114, 35-49.
    - Sixsmith, J., Oliver, S., & Lymburner, L. (2013). A hybrid approach to automated Landsat pixel quality. In, Geoscience and Remote Sensing Symposium (IGARSS), 2013 IEEE International (pp. 4146-4149).
    - Strahler, A.H., and Muller, J.-P. (1999) MODIS BRDF/Albedo Product: Algorithm Theoretical Basis Document Version 5.0. http://modis.gsfc.nasa.gov/data/atbd/atbd_mod09.pdf
    - TM World Borders vector file: http://thematicmapping.org/downloads/world_borders.php
    - USGS (2012a) Landsat Thematic Mapper (TM) Level 1 (L1) Data Format Control Book (DFCB). LS-DFCB-20 Version 4.0. USGS, USA. http://landsat.usgs.gov/documents/LS-DFCB-20.pdf
    - USGS (2012b) Landsat 7 ETM+ Level 1 Product Data Format Control Book (DFCB). LS-DFCB-04 Version 15.0.  http://landsat.usgs.gov/documents/LS-DFCB-04.pdf
    - Vincenty, T. (1975) Direct and Inverse Solutions of Geodesies on the Ellipsoid with Application of Nested Equations. Survey Review 23, 88-93.
    - Zhu, Z. and Woodcock, C. E. (2012) Object-based cloud and cloud shadow detection in Landsat imagery. Remote Sensing of Environment 118, 83-94.
    - http://dx.doi.org/10.4225/25/55EF55788BAC1

storage:
  driver: NetCDF CF

  crs: EPSG:3577
  tile_size:
          x: 100000.0
          y: 100000.0
  resolution:
          x: 25
          y: -25
  chunking:
      x: 200
      y: 200
      time: 5
  dimension_order: ['time', 'y', 'x']

measurements:
    - name: pixelquality
      dtype: int16
      nodata: 0
      resampling_method: nearest
      src_varname: pqa
      zlib: True
      fletcher32: True
      attrs:
          standard_name: surface_bidirectional_reflectance status_flag
          coverage_content_type: qualityInformation
