# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, '/home/omad/dev/digitalearthau/digitalearthau')

from glob import glob

# -- Project information -----------------------------------------------------

project = 'digitalearthau'
copyright = '2020, Geoscience Australia'
author = 'Digital Earth Australia Developers'

# Change the name from index to Home to become the Front Page of the GitHub Wiki
# these docs are published to.
master_doc = 'Home'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    'sphinx_rst_builder',
    'sphinx_click.ext',

]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# -- Extension configuration -------------------------------------------------


# -- Options for man page output -------------------------------------------------

# See http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-manual-page-output
pages = [filename.split('.')[0] for filename in glob('dea-*.rst')]
man_pages = [
    # (startdocname, name, description, authors, section)
    (page, page, "", "", 1)
    for page in pages
]

# -- Options for RST output -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
