name: eo
description: Minimal eo metadata for products without custom fields.
dataset:
    id: ['id']
    creation_dt: ['creation_dt']
    label: ['ga_label']
    measurements: ['image', 'bands']
    grid_spatial: ['grid_spatial', 'projection']
    format: ['format', 'name']
    sources: ['lineage', 'source_datasets']

    search_fields:
        platform:
            description: Platform code
            offset: [platform, code]

        instrument:
            description: Instrument name
            offset: [instrument, name]

        product_type:
            description: Product code
            offset: [product_type]

        format:
            description: File format (GeoTIFF, NetCDF)
            offset: [format, name]
            indexed: false

        lat:
            description: Latitude range
            type: double-range
            max_offset:
            - [extent, coord, ur, lat]
            - [extent, coord, lr, lat]
            - [extent, coord, ul, lat]
            - [extent, coord, ll, lat]
            min_offset:
            - [extent, coord, ur, lat]
            - [extent, coord, lr, lat]
            - [extent, coord, ul, lat]
            - [extent, coord, ll, lat]

        lon:
            description: Longitude range
            type: double-range
            max_offset:
            - [extent, coord, ul, lon]
            - [extent, coord, ur, lon]
            - [extent, coord, ll, lon]
            - [extent, coord, lr, lon]
            min_offset:
            - [extent, coord, ul, lon]
            - [extent, coord, ur, lon]
            - [extent, coord, ll, lon]
            - [extent, coord, lr, lon]

        time:
            description: Acquisition time
            type: datetime-range
            min_offset:
            - [extent, from_dt]
            max_offset:
            - [extent, to_dt]

---

name: telemetry
description: |
    telemetry datasets.
    Type of datasets produced by the eodatasets library.
    (or of similar structure)
    https://github.com/GeoscienceAustralia/eo-datasets
dataset:
    id: ['id']
    creation_dt: ['creation_dt']
    format: ['format', 'name']
    label: ['ga_label']
    sources: ['lineage', 'source_datasets']

    search_fields:
        platform:
            description: Platform code
            offset: [platform, code]

        instrument:
            description: Instrument name
            offset: [instrument, name]

        product_type:
            description: Product code
            offset: [product_type]

        time:
            description: Acquisition time
            type: datetime-range
            min_offset:
            - [acquisition, aos]
            max_offset:
            - [acquisition, los]

        gsi:
            description: Ground Station Identifier (eg. ASA)
            offset: [acquisition, groundstation, code]
            indexed: false

        orbit:
            description: Orbit number
            offset: [acquisition, platform_orbit]


---

name: landsat_scene
description: |
    Scene-based Landsat data
dataset:
    id: ['id']
    creation_dt: ['creation_dt']
    label: ['ga_label']
    measurements: ['image', 'bands']
    grid_spatial: ['grid_spatial', 'projection']
    format: ['format', 'name']
    sources: ['lineage', 'source_datasets']

    search_fields:
        platform:
            description: Platform code
            offset: [platform, code]

        instrument:
            description: Instrument name
            offset: [instrument, name]

        product_type:
            description: Product code
            offset: [product_type]
            indexed: false

        format:
            description: File format (GeoTIFF, NetCDF)
            offset: [format, name]
            indexed: false

        lat:
            description: Latitude range
            type: double-range
            max_offset:
            - [extent, coord, ur, lat]
            - [extent, coord, lr, lat]
            - [extent, coord, ul, lat]
            - [extent, coord, ll, lat]
            min_offset:
            - [extent, coord, ur, lat]
            - [extent, coord, lr, lat]
            - [extent, coord, ul, lat]
            - [extent, coord, ll, lat]

        lon:
            description: Longitude range
            type: double-range
            max_offset:
            - [extent, coord, ul, lon]
            - [extent, coord, ur, lon]
            - [extent, coord, ll, lon]
            - [extent, coord, lr, lon]
            min_offset:
            - [extent, coord, ul, lon]
            - [extent, coord, ur, lon]
            - [extent, coord, ll, lon]
            - [extent, coord, lr, lon]

        time:
            description: Acquisition time
            type: datetime-range
            min_offset:
            - [extent, from_dt]
            - [extent, center_dt]
            max_offset:
            - [extent, to_dt]
            - [extent, center_dt]

        gsi:
            description: Ground Station Identifier (eg. ASA)
            offset: [acquisition, groundstation, code]
            indexed: false

        orbit:
            description: Orbit number
            offset: [acquisition, platform_orbit]
            indexed: false

        sat_path:
            description: Landsat path
            type: numeric-range
            min_offset:
            - [image, satellite_ref_point_start, x]
            max_offset:
            - [image, satellite_ref_point_end, x]
            # If an end is not specified, use the start.
            - [image, satellite_ref_point_start, x]

        sat_row:
            description: Landsat row
            type: numeric-range
            min_offset:
            - [image, satellite_ref_point_start, y]
            max_offset:
            - [image, satellite_ref_point_end, y]
            # If an end is not specified, use the start.
            - [image, satellite_ref_point_start, y]

---

name: landsat_l1_scene
description: |
    Scene-based Level1 Landsat data
dataset:
    id: ['id']
    creation_dt: ['creation_dt']
    label: ['ga_label']
    measurements: ['image', 'bands']
    grid_spatial: ['grid_spatial', 'projection']
    format: ['format', 'name']
    sources: ['lineage', 'source_datasets']

    search_fields:
        platform:
            description: Platform code
            offset: [platform, code]

        instrument:
            description: Instrument name
            offset: [instrument, name]

        product_type:
            description: Product code
            offset: [product_type]
            indexed: false

        format:
            description: File format (GeoTIFF, NetCDF)
            offset: [format, name]
            indexed: false

        lat:
            description: Latitude range
            type: double-range
            max_offset:
            - [extent, coord, ur, lat]
            - [extent, coord, lr, lat]
            - [extent, coord, ul, lat]
            - [extent, coord, ll, lat]
            min_offset:
            - [extent, coord, ur, lat]
            - [extent, coord, lr, lat]
            - [extent, coord, ul, lat]
            - [extent, coord, ll, lat]

        lon:
            description: Longitude range
            type: double-range
            max_offset:
            - [extent, coord, ul, lon]
            - [extent, coord, ur, lon]
            - [extent, coord, ll, lon]
            - [extent, coord, lr, lon]
            min_offset:
            - [extent, coord, ul, lon]
            - [extent, coord, ur, lon]
            - [extent, coord, ll, lon]
            - [extent, coord, lr, lon]

        time:
            description: Acquisition time
            type: datetime-range
            min_offset:
            - [extent, from_dt]
            - [extent, center_dt]
            max_offset:
            - [extent, to_dt]
            - [extent, center_dt]

        gsi:
            description: Ground Station Identifier (eg. ASA)
            offset: [acquisition, groundstation, code]
            indexed: false

        orbit:
            description: Orbit number
            offset: [acquisition, platform_orbit]
            indexed: false

        ancillary_quality:
            description: Ancillary quality
            offset: [lineage, ancillary_quality]
            indexed: false

        gqa:
            description: GQA Circular error probable (90%)
            type: double
            offset: [gqa, cep90]
            indexed: false
        gqa_error_message:
            description: GQA Error Message
            offset: [gqa, error_message]
            indexed: false
        gqa_final_gcp_count:
            description: GQA GCP Count
            offset: [gqa, final_gcp_count]
            type: integer
            indexed: false
        gqa_ref_source:
            description: GQA reference imagery collection name
            offset: [gqa, ref_source]
            indexed: false
        gqa_cep90:
            description: Circular error probable (90%) of the values of the GCP residuals
            offset: [gqa, residual, cep90]
            type: double
            indexed: false
        gqa_abs_xy:
            description: Absolute value of the total GCP residual
            offset: [gqa, residual, abs, xy]
            type: double
            indexed: false
        gqa_abs_iterative_mean_xy:
            description: Mean of the absolute values of the GCP residuals after removal of outliers
            offset: [gqa, residual, abs_iterative_mean, xy]
            type: double
            indexed: false
        gqa_iterative_mean_xy:
            description: Mean of the values of the GCP residuals after removal of outliers
            offset: [gqa, residual, iterative_mean, xy]
            type: double
            indexed: false
        gqa_iterative_stddev_xy:
            description: Standard Deviation of the values of the GCP residuals after removal of outliers
            offset: [gqa, residual, iterative_stddev, xy]
            type: double
            indexed: false
        gqa_mean_xy:
            description: Mean of the values of the GCP residuals
            offset: [gqa, residual, mean, xy]
            type: double
            indexed: false
        gqa_stddev_xy:
            description: Standard Deviation of the values of the GCP residuals
            offset: [gqa, residual, stddev, xy]
            type: double
            indexed: false

        sat_path:
            description: Landsat path
            type: numeric-range
            min_offset:
            - [image, satellite_ref_point_start, x]
            max_offset:
            - [image, satellite_ref_point_end, x]
            # If an end is not specified, use the start.
            - [image, satellite_ref_point_start, x]

        sat_row:
            description: Landsat row
            type: numeric-range
            min_offset:
            - [image, satellite_ref_point_start, y]
            max_offset:
            - [image, satellite_ref_point_end, y]
            # If an end is not specified, use the start.
            - [image, satellite_ref_point_start, y]
