---
name: eo3
description: Default EO3 with no custom fields
dataset:
  id: [id] # No longer configurable in newer ODCs.
  sources: [lineage, source_datasets] # No longer configurable in newer ODCs.

  grid_spatial: [grid_spatial, projection]
  measurements: [measurements]
  creation_dt: [properties, 'odc:processing_datetime']
  label: [label]
  format: [properties, 'odc:file_format']

  search_fields:
    platform:
      description: Platform code
      offset: [properties, 'eo:platform']
      indexed: false

    instrument:
      description: Instrument name
      offset: [properties, 'eo:instrument']
      indexed: false

    product_family:
      description: Product family code
      offset: [properties, 'odc:product_family']
      indexed: false

    region_code:
      description: >
        Spatial reference code from the provider.
        For Landsat region_code is a scene path row:
                '{:03d}{:03d}.format(path,row)'.
        For Sentinel it is MGRS code.
        In general it is a unique string identifier that datasets
        covering roughly the same spatial region share.

      offset: [properties, 'odc:region_code']

    dataset_maturity:
      description: One of - final|interim|nrt  (near real time)
      offset: [properties, 'dea:dataset_maturity']
      indexed: false

    time:
      description: Acquisition time range
      type: datetime-range
      min_offset:
        - [properties, 'dtr:start_datetime']
        - [properties, datetime]
      max_offset:
        - [properties, 'dtr:end_datetime']
        - [properties, datetime]

    # LonLat bounding box, generated on the fly from:
    #  `grids`, `crs` and `geometry` of the new metadata format
    #
    # Bounding box is defined by two ranges:
    #   [lon.begin, lon.end] -- Longitude
    #   [lat.begin, lat.end] -- Latitude
    #
    # Note that STAC is using `bbox` for the same thing as following:
    #
    #     bbox: [left, bottom, right, top]
    #              0      1      2     3
    #             lon    lat    lon   lat
    #
    # But MetadataType does not support integer index keys, so...
    #   BoundingBox: [lon.begin, lat.begin, lon.end, lat.end]

    lon:
      description: Longitude range
      type: double-range
      min_offset:
        - [extent, lon, begin]
      max_offset:
        - [extent, lon, end]

    lat:
      description: Latitude range
      type: double-range
      min_offset:
        - [extent, lat, begin]
      max_offset:
        - [extent, lat, end]
