---
name: eo3_sentinel
description: EO3 with common Sentinel fields
dataset:
  id: [id]  # No longer configurable in newer ODCs.
  sources: [lineage, source_datasets]  # No longer configurable in newer ODCs.

  grid_spatial: [grid_spatial, projection]
  measurements: [measurements]
  creation_dt: [properties, 'odc:processing_datetime']
  label: [label]
  format: [properties, 'odc:file_format']

  search_fields:
    platform:
      description: Platform code
      offset: [properties, 'eo:platform']
      indexed: false

    instrument:
      description: Instrument name
      offset: [properties, 'eo:instrument']
      indexed: false

    product_family:
      description: Product family code
      offset: [properties, 'odc:product_family']
      indexed: false

    region_code:
      description: >
        Spatial reference code from the provider.

        For Sentinel it is MGRS code.

      offset: [properties, 'odc:region_code']

    crs_raw:
      description: |
        The raw CRS string as it appears in metadata

        (e.g. ‘epsg:32654’)
      offset: ['crs']
      indexed: false

    dataset_maturity:
      description: |
        One of - final|interim|nrt  (near real time)

        The maturity level of the dataset; options include ‘nrt’
        (ARD processing date less than 48 hours after acquisition date),
        ‘interim’ (processed using fallback water vapour or BRDF data) and
        ‘final’
      offset: [properties, 'dea:dataset_maturity']
      indexed: false

    cloud_cover:
      description: |
        The proportion (from 0 to 100) of the dataset's valid data area that contains cloud pixels
      type: double
      offset: [properties, 'eo:cloud_cover']

    time:
      description: Acquisition time range
      type: datetime-range
      min_offset:
        - [properties, 'dtr:start_datetime']
        - [properties, datetime]
      max_offset:
        - [properties, 'dtr:end_datetime']
        - [properties, datetime]

    # LonLat bounding box, generated on the fly from:
    #  `grids`, `crs` and `geometry` of the new metadata format
    #
    # Bounding box is defined by two ranges:
    #   [lon.begin, lon.end] -- Longitude
    #   [lat.begin, lat.end] -- Latitude
    #
    # Note that STAC is using `bbox` for the same thing as following:
    #
    #     bbox: [left, bottom, right, top]
    #              0      1      2     3
    #             lon    lat    lon   lat
    #
    # But MetadataType does not support integer index keys, so...
    #   BoundingBox: [lon.begin, lat.begin, lon.end, lat.end]

    lon:
      description: Longitude range
      type: double-range
      min_offset:
        - [extent, lon, begin]
      max_offset:
        - [extent, lon, end]

    lat:
      description: Latitude range
      type: double-range
      min_offset:
        - [extent, lat, begin]
      max_offset:
        - [extent, lat, end]

    # semi-auto generated below
    eo_gsd:
      # The nominal distance between pixel centers available, in meters.
      description: |
        Ground sampling distance of the sensor’s best resolution band
        in metres; represents the size (or spatial resolution) of one pixel.
      indexed: false
      offset:
        - properties
        - eo:gsd
      type: double
    eo_sun_azimuth:
      description: |
        The azimuth angle of the sun at the moment of acquisition, in degree units measured clockwise from due north
      indexed: false
      offset:
        - properties
        - eo:sun_azimuth
      type: double
    eo_sun_elevation:
      description: |
        The elevation angle of the sun at the moment of acquisition, in degree units relative to the horizon.
      indexed: false
      offset:
        - properties
        - eo:sun_elevation
      type: double
    sentinel_product_name:
      description: |
        ESA product URI, with the '.SAFE' ending removed.

        (e.g. 'S2A_MSIL1C_20220303T000731_N0400_R073_T56LNM_20220303T012845')
      indexed: false
      offset:
        - properties
        - sentinel:product_name
    sentinel_tile_id:
      description: |
          Granule ID according to the ESA naming convention

          (e.g. ‘S2A_OPER_MSI_L1C_TL_SGS__20161214T040601_A007721_T53KRB_N02.04’)
      indexed: false
      offset:
        - properties
        - sentinel:sentinel_tile_id
    sentinel_datastrip_id:
      description: |
          Unique identifier for a datastrip relative to a given Datatake.

          (e.g. ‘S2A_OPER_MSI_L1C_DS_SGS__20161214T040601_S20161214T005840_N02.04’)
      indexed: false
      offset:
        - properties
        - sentinel:datastrip_id
