specification:
  transform: fc.virtualproduct.FractionalCover

  product: ga_ls8c_ard_3
  measurements: ['nbart_green', 'nbart_red', 'nbart_nir', 'nbart_swir_1', 'nbart_swir_2']
  measurement_renames:
    nbart_green: green
    nbart_red: red
    nbart_nir: nir
    nbart_swir_1: swir1
    nbart_swir_2: swir2

  regression_coefficients:
    blue:
      - 0.00041
      - 0.97470
    green:
      - 0.00289
      - 0.99779
    red:
      - 0.00274
      - 1.00446
    nir:
      - 0.00004
      - 0.98906
    swir1:
      - 0.00256
      - 0.99467
    swir2:
      - -0.00327
      - 1.02551
  input:
    product: ls8_nbart_albers
    measurements: [green, red, nir, swir1, swir2]

metadata:
  product_family: fractional_cover
  producer: ga.gov.au
  dataset_version: 2.0.0

file_output:
  location: '/local/u46/dra547/sandpit/odc_testing/'
  dtype: # single value, or value per band
  nodata: # single value, or value per band
