task_generation:
  input_product: ls8_nbart_albers
  output_product: ls8_fc_albers

virtual_product_specification:
  transform: digitalearthau.vpmapper.virtualproduct.FakeFractionalCover

  regression_coefficients:
    blue:
      - 0.00041
      - 0.97470
    green:
      - 0.00289
      - 0.99779
    red:
      - 0.00274
      - 1.00446
    nir:
      - 0.00004
      - 0.98906
    swir1:
      - 0.00256
      - 0.99467
    swir2:
      - -0.00327
      - 1.02551
  input:
        product: ls8_nbart_albers
        measurements: [green, red, nir, swir1, swir2]

file_output:
  location: '/local/u46/dra547/sandpit/odc_testing/LS8_OLI_FC/'
  file_path_template: '{region_code}/LS8_OLI_FC_3577_{start_time}_v{version}.tif'

dataset_doc_template:
  product_type: fractional_cover
