name: camden_insar_radarsat_velocity
description: Camden InSAR Radarsat Velocity
metadata_type: eo3

metadata:
    product:
        name: camden_insar_radarsat_velocity

measurements:
    - name: 'ew'
      aliases:
      - eastwest
      dtype: float32
      nodata: -9999
      units: 'mm/year'
    - name: 'ud'
      aliases:
      - updown
      dtype: float32
      nodata: -9999
      units: 'mm/year'