name: camden_insar_radarsat_displacement
description: Camden InSAR Radarsat Displacement
metadata_type: eo3

metadata:
    product:
        name: camden_insar_radarsat_displacement

measurements:
    - name: 'ew'
      aliases:
      - eastwest
      dtype: float32
      nodata: -9999
      units: 'mm'
    - name: 'ud'
      aliases:
      - updown
      dtype: float32
      nodata: -9999
      units: 'mm'
