---
name: dsm1sv10
description: DSM 1sec Version 1.0
metadata_type: eo

metadata:
    platform:
        code: SRTM
    format:
        name: GeoTIFF
    instrument:
        name: SIR
    product_type: DEM
storage:
    crs: EPSG:4326
    resolution:
        longitude: 0.000277777777780
        latitude: -0.000277777777780
    dimension_order: ["time", "latitude", "longitude"]

measurements:
      - name: elevation
        dtype: float32
        nodata: .nan
        units: 'metre'
