---
description: 'Landsat 5 Fractional Cover 25 metre, 100km tile, Australian Albers
    Equal Area projection (EPSG:3577)'
managed: true
measurements:
  - aliases:
      - bare
    dtype: int8
    name: BS
    nodata: -1
    units: percent
  - aliases:
      - green_veg
    dtype: int8
    name: PV
    nodata: -1
    units: percent
  - aliases:
      - dead_veg
    dtype: int8
    name: NPV
    nodata: -1
    units: percent
  - aliases:
      - err
    dtype: int8
    name: UE
    nodata: -1
    units: '1'
metadata:
  instrument:
    name: TM
  platform:
    code: LANDSAT_5
  product_type: fractional_cover
metadata_type: eo
name: ls5_fc_albers
storage:
  crs: EPSG:3577
  resolution:
    x: 25
    y: -25
  tile_size:
    x: 100000.0
    y: 100000.0
---
description: 'Landsat 7 Fractional Cover 25 metre, 100km tile, Australian Albers
    Equal Area projection (EPSG:3577)'
managed: true
measurements:
  - aliases:
      - bare
    dtype: int8
    name: BS
    nodata: -1
    units: percent
  - aliases:
      - green_veg
    dtype: int8
    name: PV
    nodata: -1
    units: percent
  - aliases:
      - dead_veg
    dtype: int8
    name: NPV
    nodata: -1
    units: percent
  - aliases:
      - err
    dtype: int8
    name: UE
    nodata: -1
    units: '1'
metadata:
  instrument:
    name: ETM
  platform:
    code: LANDSAT_7
  product_type: fractional_cover
metadata_type: eo
name: ls7_fc_albers
storage:
  crs: EPSG:3577
  resolution:
    x: 25
    y: -25
  tile_size:
    x: 100000.0
    y: 100000.0
---
description: 'Landsat 8 Fractional Cover 25 metre, 100km tile, Australian Albers
    Equal Area projection (EPSG:3577)'
managed: true
measurements:
  - aliases:
      - bare
    dtype: int8
    name: BS
    nodata: -1
    units: percent
  - aliases:
      - green_veg
    dtype: int8
    name: PV
    nodata: -1
    units: percent
  - aliases:
      - dead_veg
    dtype: int8
    name: NPV
    nodata: -1
    units: percent
  - aliases:
      - err
    dtype: int8
    name: UE
    nodata: -1
    units: '1'
metadata:
  instrument:
    name: OLI_TIRS
  platform:
    code: LANDSAT_8
  product_type: fractional_cover
metadata_type: eo
name: ls8_fc_albers
storage:
  crs: EPSG:3577
  resolution:
    x: 25
    y: -25
  tile_size:
    x: 100000.0
    y: 100000.0
