name: mangrove_extent_cover_albers
description: Mangroves conver extent and classes 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)

metadata_type: eo

metadata:
  product_type: mangrove_extent_cover
  format:
    name: GeoTIFF
  platform:
    code: LANDSAT_5,LANDSAT_7,LANDSAT_8
  instrument:
    name: TM,ETM+,OLI

storage:
  driver: GeoTIFF
  crs: EPSG:3577
  tile_size:
    x: 100000.0
    y: 100000.0
  resolution:
    x: 25
    y: -25
  chunking:
    x: 512
    y: 512
    time: 1
  dimension_order: [time, y, x]

measurements:
  - name: extent
    dtype: int16
    nodata: -1
    units: '1'

  - name: canopy_cover_class
    dtype: int16
    nodata: -1
    units: '1'
