---
description: 'Historic Flood Mapping Water Observations from Space'
managed: true
measurements:
      - name: water
        dtype: int16
        nodata: 1
        units: '1'
        flags_definition:
            dry:
              bits: [7, 6, 5, 4, 3, 1, 0]  # Ignore sea mask
              description: Clear and dry
              values: {0: true}
            nodata:
              bits: 0
              description: No data
              values: {1: true}
            noncontiguous:
              bits: 1
              description: At least one EO band is missing over over/undersaturated
              values: {0: false, 1: true}
            sea:
              bits: 2
              description: Sea
              values: {0: false, 1: true}
            terrain_or_low_angle:
              bits: 3
              description: Terrain shadow or low solar angle
              values: {0: false, 1: true}
            high_slope:
              bits: 4
              description: High slope
              values: {0: false, 1: true}
            cloud_shadow:
              bits: 5
              description: Cloud shadow
              values: {0: false, 1: true}
            cloud:
              bits: 6
              description: Cloudy
              values: {0: false, 1: true}
            water_observed:
              bits: 7
              description: Classified as water by the decision tree
              values: {0: false, 1: true}
            wet:
              bits: [7, 6, 5, 4, 3, 1, 0]  # Ignore sea mask
              description: Clear and Wet
              values: {128: true}
metadata:
  product_type: wofs
  format:
    name: NetCDF
metadata_type: eo
name: wofs_albers
storage:
  chunking:
    time: 5
    x: 200
    y: 200
  crs: EPSG:3577
  dimension_order:
    - time
    - y
    - x
  driver: 'NetCDF CF'
  resolution:
    x: 25
    y: -25
  tile_size:
    x: 100000.0
    y: 100000.0
