

task_generation:
  input_product: ls8_nbart_albers
  output_product: ls8_fc_albers




virtual_product_specification:
  transform: fc.new.virtualproduct.FakeFractionalCover

  regression_coefficients:
    blue:
      - 0.00041
      - 0.97470
    green:
      - 0.00289
      - 0.99779
    red:
      - 0.00274
      - 1.00446
    nir:
      - 0.00004
      - 0.98906
    swir1:
      - 0.00256
      - 0.99467
    swir2:
      - -0.00327
      - 1.02551
  input:
        product: ls8_nbart_albers
        measurements: [green, red, nir, swir1, swir2]


file_output:
  location: '/local/u46/dra547/sandpit/odc_testing/LS8_OLI_FC/'
  file_path_template: '{region_code}/LS8_OLI_FC_3577_{start_time}_v{version}.tif'



dataset_doc_template:
  product_type: fractional_cover

#measurements:
#  - name: BS
#    src_var: BS
#    units: "percent"
#    dtype: int8
#    nodata: -1
#    zlib: True
#    fletcher32: True
#    attrs:
#      long_name: "Bare ground fraction percentage"
#      comment: "Fraction of bare ground including rock, bare and disturbed soil, within the Landsat pixel as percentages"
#      alias: "bare"
#      coverage_content_type: modelResult
#    aliases: ["bare"]
#  - name: PV
#    src_var: PV
#    units: "percent"
#    dtype: int8
#    nodata: -1
#    zlib: True
#    fletcher32: True
#    attrs:
#      long_name: "Green cover fraction percentage"
#      comment: "Fraction of green cover including green groundcover and green leaf material over all strata, within the Landsat pixel, as percentages"
#      alias: "green"
#      coverage_content_type: modelResult
#    aliases: ["green_veg"]
#  - name: NPV
#    src_var: NPV
#    units: "percent"
#    dtype: int8
#    nodata: -1
#    zlib: True
#    fletcher32: True
#    attrs:
#      long_name: "Non-green cover fraction percentage"
#      comment: "Fraction of non green cover including litter, dead leaf and branches over all strata, within the Landsat pixel, as percentages"
#      alias: "dead"
#      coverage_content_type: modelResult
#    aliases: ["dead_veg"]
#  - name: UE
#    src_var: UE
#    units: "1"
#    dtype: int8
#    nodata: -1
#    zlib: True
#    fletcher32: True
#    attrs:
#      long_name: "Unmixing error"
#      comment: "Eclidean Norm of the Residual Vector"
#      alias: "err"
#      coverage_content_type: qualityInformation
#    aliases: ["err"]

