# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [develop, fix/ci]
  pull_request:
    branches: [develop, fix/ci]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:10
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
          activate-environment: dea
          python-version: 3.6
          channels: conda-forge
          allow-softlinks: true
          channel-priority: strict
          show-channel-urls: true
          use-only-tar-bz2: true
    - name: Test conda action
      shell: 'bash -l {0}'
      run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
    - name: Create Integration Test Database
      run: |
        sudo apt-get -yqq install postgresql-client
        createdb dea_integration
      env:
        # The hostname used to communicate with the PostgreSQL service container
        PGHOST: localhost
        # The default PostgreSQL port
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: postgres

    - name: Install dependencies
      shell: 'bash -l {0}'
      run: |
        conda update -n base -c defaults conda
        conda create -n dea python=3.6 datacube boltons pydash ciso8601 cattrs ruamel.yaml dawg structlog flake8
        conda activate dea
        python setup.py bdist_wheel
        pip install dist/*.whl
    - name: Lint with flake8
      shell: 'bash -l {0}'
      run: |
        conda activate dea
        ./check-code.sh integration_tests

        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: 'bash -l {0}'
      run: |
        conda activate dea
        pytest
